/**
 * Regenerates public/sitemap.xml from static routes + src/blog/posts/*.mdx.
 * Run before production build: npm run generate:sitemap
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { listBlogPosts } from './blog-posts-manifest.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'public', 'sitemap.xml');
const SITE_ORIGIN = 'https://gridsmith.io';

/** @type {{ path: string, changefreq: string, priority: string }[]} */
const STATIC_ROUTES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/baseplate', changefreq: 'weekly', priority: '0.95' },
  { path: '/tile-builder', changefreq: 'weekly', priority: '0.95' },
  { path: '/tiles', changefreq: 'monthly', priority: '0.9' },
  { path: '/blog', changefreq: 'weekly', priority: '0.88' },
  { path: '/about', changefreq: 'monthly', priority: '0.85' },
  { path: '/profile', changefreq: 'monthly', priority: '0.4' },
  { path: '/tos', changefreq: 'yearly', priority: '0.3' },
  { path: '/privacy', changefreq: 'yearly', priority: '0.3' },
];

function urlEntry(loc, changefreq, priority, lastmod) {
  const lastmodTag = lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : '';
  return `  <url>
    <loc>${loc}</loc>${lastmodTag}
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

const blogPosts = listBlogPosts();
const lines = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  '  <!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand -->',
  ...STATIC_ROUTES.map((r) =>
    urlEntry(`${SITE_ORIGIN}${r.path}`, r.changefreq, r.priority)
  ),
  ...blogPosts.map((p) =>
    urlEntry(`${SITE_ORIGIN}/blog/${p.slug}`, 'monthly', '0.75', p.date)
  ),
  '</urlset>',
  '',
];

fs.writeFileSync(OUT, lines.join('\n'));
console.log(`Wrote ${OUT} (${STATIC_ROUTES.length} static + ${blogPosts.length} blog URLs)`);
